### ISSUE TITLE
Output is just black

### ISSUE THREAD

**Issue by youyuge34** [sniklaus/pytorch-sepconv#23]
I installed and run the code successfully on floydhub, but  my output photo is just whole balck.
There is no warning message.
Please help!

**Comment by youyuge34** [comment]
The install steps works well. When I run the ```python run.py``` , i get the following error. I use the Nvida K80.
```
THCudaCheck FAIL file=src/SeparableConvolution_kernel.cu line=65 error=48 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "run.py", line 259, in <module>
    process(tensorInputFirst, tensorInputSecond, tensorOutput)
  File "run.py", line 224, in process
    variablePaddingOutput = modulePaddingOutput(moduleNetwork(variablePaddingFirst, variablePaddingSecond))
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "run.py", line 166, in forward
    variableDot1 = SeparableConvolution()(self.modulePad(variableInput1), self.moduleVertical1(variableCombine), self.moduleHorizontal1(variableCombine))
  File "/output/SeparableConvolution.py", line 34, in forward
    output
  File "/usr/local/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 197, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: cuda runtime error (48) : no kernel image is available for execution on the device at src/SeparableConvolution_kernel.cu:65
```

**Comment by sniklaus** [comment]
That looks like an issue with the FloydHub environment. I am afraid that I cannot provide support in this regard and would recommend reaching out to their support, my apologies.

**Comment by youyuge34** [comment]
I figured out the reason. Just because the calculation capability of Tesla k80 is too low. I used the aws p3 instance which has GPU Tesla P100 works well.

**Comment by sniklaus** [comment]
I am happy to hear that! You can alternatively also modify the `gpu-architecture` as well as the `gpu-code` in the `install.bash`.

https://github.com/sniklaus/pytorch-sepconv/blob/a6f1f6920053c7372bfae7e0d08c17453c7f0152/install.bash#L5

**Comment by sniklaus** [comment]
I just updated the code and it now uses CuPy, which should allow you to run it on a Tesla K80 without any issues.

**Comment by youyuge34** [comment]
THX！
